version: 2

before:
  hooks:
    - make dashboard-build

builds:
  - id: certhealthz
    main: .
    binary: certhealthz
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/thev1ndu/certhealthz/cmd.Version={{ .Tag }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: certhealthz
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: thev1ndu
    name: certhealthz
